Repository googleapis/nodejs-redis, pull requests merged in 2019-05, with the labels that each got.

#155 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#154 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#156 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#159 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
Labels: cla: yes

#160 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#161 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#158 build: only pipe to codecov if tests run on Node 10
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#162 fix: DEADLINE_EXCEEDED error is no longer retried
  src/v1/cloud_redis_client_config.json
  src/v1beta1/cloud_redis_client_config.json
  synth.metadata
Labels: cla: yes

#164 fix: DEADLINE_EXCEEDED retry code is idempotent
  src/v1/cloud_redis_client_config.json
  src/v1beta1/cloud_redis_client_config.json
  synth.metadata
Labels: cla: yes

#166 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#170 chore: release 1.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#172 refactor: drop dependency on lodash.merge and update links
  package.json
  src/v1/cloud_redis_client.js
  src/v1beta1/cloud_redis_client.js
  synth.metadata
Labels: cla: yes

#173 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#174 build: add configuration for automated doc deployemnt
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#175 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#176 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
