Repository googleapis/nodejs-redis, pull requests merged in 2020-04, with the labels that each got.

#300 build: set AUTOSYNTH_MULTIPLE_COMMITS=true for context aware commits
  synth.py
Labels: automerge, cla: yes

#303 docs: updates to proto comments
  protos/google/cloud/redis/v1/cloud_redis.proto
  protos/google/cloud/redis/v1beta1/cloud_redis.proto
  synth.metadata
Labels: cla: yes

#304 chore: remove duplicate mocha config
  .mocharc.json
Labels: automerge, cla: yes

#375 chore: run the generator
  .jsdoc.js
  .prettierrc.js
  package.json
  protos/protos.js
  protos/protos.json
  synth.metadata
  test/gapic_cloud_redis_v1.ts
  test/gapic_cloud_redis_v1beta1.ts
  tslint.json
Labels: automerge, cla: yes

#376 fix: remove eslint, update gax, fix generated protos, run the generator
  package.json
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#377 build: remove unused codecov config
  codecov.yaml
Labels: automerge, cla: yes

#378 chore: update lint ignore files
  .eslintignore
  .prettierignore
Labels: automerge, cla: yes

#379 chore: remove unused dev packages
  package.json
Labels: automerge

#383 chore: run fix instead of lint in synthfile
  synth.py
Labels: automerge, cla: yes

#387 build: update CI coverage and fix linting issues
  .github/workflows/ci.yaml
  protos/protos.js
  synth.metadata
  system-test/install.ts
Labels: cla: yes

#388 chore: update npm scripts and synth.py
  package.json
  synth.py
Labels: automerge, cla: yes
