Repository googleapis/nodejs-redis, pull requests merged in 2020-05, with the labels that each got.

#390 feat: check status of long running operation by its name
  protos/protos.js
  src/v1/cloud_redis_client.ts
  src/v1beta1/cloud_redis_client.ts
  synth.metadata
  test/gapic_cloud_redis_v1.ts
  test/gapic_cloud_redis_v1beta1.ts
Labels: automerge, cla: yes

#392 fix: synth.py clean up for multiple version
  protos/protos.js
  src/index.ts
  synth.metadata
  synth.py
Labels: cla: yes

#393 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
