Repository googleapis/nodejs-redis, pull requests merged in 2020-07, with the labels that each got.

#407 build: use bazel build
  src/v1/cloud_redis_client_config.json
  src/v1beta1/cloud_redis_client_config.json
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#408 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#409 build: compile protos before running tsc
  package.json
Labels: cla: yes

#411 feat: add redis function to upgrade version upon request
  protos/google/cloud/redis/v1/cloud_redis.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1/cloud_redis_client.ts
  src/v1/cloud_redis_client_config.json
  synth.metadata
  test/gapic_cloud_redis_v1.ts
Labels: cla: yes, context: none

#412 build: typo in .gittatribute, request upgrade instance
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: partial

#414 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#417 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none

#418 build: missing closing paren in publish script, add config files for cloud-rad for nodejs
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#419 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#420 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#421 chore: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full, kokoro:run

#422 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#423 build: update protos
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: none
